#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
####@
name: Compile R619AC3 TVH x-wrt Images  

on:
 #repository_dispatch:
    #types: [ipq40xx_completed]
 workflow_dispatch:    
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  #push:
   #branches: 
    #- master
 #schedule:
  #  - cron: "45 15 * * *"
  #release:
   # types: [published]
  #watch:
    #types: started

  #workflow_dispatch:    
    
env:
  #####change model here ####@# 
  ROUTER_MODEL: r619ac
  TVH: true
  CONFIG_FILENAME_FOR_2ND_COMPILE: config.r619ac
  BUILD_KERNEL_MODULES: true
  DRIVERS_DIR: x-wrt/bin/targets/ipq40xx/drivers
  KERNEL_CONFIG: 'myconfig/kernel_config.r619ac'
  KERNEL_CONFIG_DIR: x-wrt/target/linux/ipq40xx
  #KERNEL_CONFIG_DIR: target/linux/ramips/mt7620
  #KERNEL_CONFIG_DIR: target/linux/ramips/mt7621
  #KERNEL_CONFIG_DIR: target/linux/mvebu
  MAKEMENU_CONFIG: false
  KERNEL_MENUCONFIG: false
  CPU_MULTI_CORE: true
  #KERNEL_VERSION: '5.15'
  KERNEL_VERSION: '6.12'                                                                            
  UPDATE_MULTI_CORE_FILE1: myconfig/sys.lua
  UPDATE_MULTI_CORE_FILE2: myconfig/processes.js
  KERNEL_MODULE: myconfig/kernel_r619ac
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  SSH_ACTIONS: true
  UPLOAD_FIRMWARE: true
  #UPLOAD_ROUTER: true
  TZ: Asia/Shanghai
  CLEARCACHE: true
  
jobs:

  build_openwrt:
    ###@####
    name: Build R619AC x-wrt TVH firmware
    #runs-on: ubuntu-latest
    #continue-on-error: true 
    runs-on: ubuntu-22.04
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: 检查项目分支
        uses: actions/checkout@main
        
      - name: Check CPU model
        run: |                                                    
          cat /proc/cpuinfo|grep model                            
          cat /proc/cpuinfo|grep proc
          echo cpu core=$(nproc)
          free
      - name: 更改设置
        run: |
          #cat /proc/cpuinfo|grep model
          #cat /proc/cpuinfo|grep proce
          chmod +x $GITHUB_WORKSPACE/$DIY_P1_SH
          $GITHUB_WORKSPACE/$DIY_P1_SH
          chmod +x $GITHUB_WORKSPACE/$DIY_P2_SH
          $GITHUB_WORKSPACE/$DIY_P2_SH
          sudo timedatectl set-timezone "$TZ"
      
      - name: Generate cache mixkey
        id: gen_cache_mixkey
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          target_device_arch_1="ipq40xx"
          #target_device_arch_1="mvebu_ipq40xx_ramips"
          #target_device_arch_1="mvebu"
          gcc_hash=$(gcc --version | sha256sum | awk '{print substr($1,1,8)}')
          #gcc_hash='37dab1b7'       
          ldd_hash=$(ldd --version | sha256sum | awk '{print substr($1,1,8)}')
          mixkey1="${target_device_arch_1}-${gcc_hash}-${ldd_hash}"
          #mixkey2="${target_device_arch_2}-${gcc_hash}-${ldd_hash}"
          echo "mixkey1=$mixkey1" >> $GITHUB_OUTPUT
     
      - name: Cache1
        uses: HiGarfield/cachewrtbuild@main 				#klever1988/cachewrtbuild@main 
        with:
          ccache: 'true'
          mixkey: ${{ steps.gen_cache_mixkey.outputs.mixkey1 }}
          #prefix: ${{ env.WORKING_DIR }}
          prefix: ${{ github.workspace }}/x-wrt
          #skip_saving: 'true'
      - name: Clear Cache
        if: env.CLEARCACHE == 'true'
        run: |
          gh extension install actions/gh-actions-cache
          REPO=${{ github.repository }}
          BRANCH="master"
          #target_device_arch_1="ipq40xx" 
          #echo "Fetching list of cache key"
          list_of_caches=$(gh actions-cache  --sort created-at list -R $REPO -B $BRANCH -L 100| cut -f 1)
          echo $list_of_caches
          no_of_cache=$(gh actions-cache list -R $REPO -B $BRANCH -L 100|wc -l)
          echo no of cache found = $no_of_cache
          if [ "$no_of_cache" -gt 6 ]
          then
          cacheKey=$(gh actions-cache  --sort created-at list -R $REPO -B $BRANCH -L 100| cut -f 1|tail -1 )
          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          echo $cacheKey
          echo "Done"
          fi
          size=`du x-wrt/staging_dir/|tail -1|awk '{print $1}'`
          if [ $size -ge 100000 ] 
          then 
            config_file="x-wrt/config.$ROUTER_MODEL.3"
            echo caches restored using config file $config_file
            echo "CACHE_RESTORED=TRUE" >> $GITHUB_ENV            
            echo "bin=bin2" >> $GITHUB_ENV
          else
            config_file="x-wrt/config.$ROUTER_MODEL.0"
            echo caches not found,using config file $config_file
            echo "CACHE_RESTORED=FALSE" >> $GITHUB_ENV   
            echo "bin=bin1" >> $GITHUB_ENV
          fi
          cp $config_file myconfig/$CONFIG_FILENAME_FOR_2ND_COMPILE                
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 安装编译环境
        env:
          SSH_ACTIONS: true
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt list --installed
          #/usr/bin/tar -xf /home/runner/work/_temp/1a144490-77f9-4c00-ae54-698cee23f6b0/cache.tgz -P -C $GITHUB_WORKSPACE -z
          #ls -alt ${{ github.workspace }}/x-wrt/staging_dir/*
          docker rmi `docker images -q`
          #sudo apt remove firefox powershell microsoft-edge* temurin* php* nginx dotnet* ubuntu-gnome-desktop gnome-shell golang* google* mysql* ruby* apach* r-*
          
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install opencc ccache build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libfuse-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          #sudo -E apt-get update
          #sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libfuse-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5 --fix-missing
          sudo apt-get purge --auto-remove azure* openjdk* firefox* powershell* microsoft-edge* temurin* r-* php* nginx dotnet* ubuntu-gnome-desktop gnome-shell golang* google* mysql* ruby* apach*
          
          sudo -E apt-get -y autoremove --purge
          #sudo pip install ply 
          #sudo -E python3 -m pip install --upgrade pip 
          #sudo -E pip install --no-cache-dir --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org pip setuptools
          sudo -E apt-get clean
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get autoremove
          sudo apt-get autoclean -y 
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo rm -rf /usr/local/lib/android
          sudo apt-get autoremove
          sudo apt-get autoclean -y 
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo rm -f /usr/local/share/chromium/chrome-linux/chrome
          sudo rm -f /opt/microsoft/msedge/msedge
          sudo rm -f $GITHUB_WORKSPACE/lede/.git/objects/pack/pack-*.pack
          df -kh
          #find /home/runner/work/_temp/ -name "*cache*"
     # - name: Run migrations
      #  run: sh ./github/scripts/migrate.sh
       # env:
        # ENVIRONMENT_VARIABLE_NAME: ${{ secrets.ENVIRONMENT_VARIABLE_NAME }}
          # echo 'HELLO_WORLD='${{ secrets.HELLO_WORLD }} >> .env // Code line 1
    
    #
      #- name: Generate configuration file
       #  run: |
         
          #rm -f ./.config*
          #touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:

          #cat >> .config <<EOF
          #CONFIG_TARGET_IMAGES_GZIP=y
          #CONFIG_KERNEL_BUILD_USER="OpenWrt-CI"
          #CONFIG_KERNEL_BUILD_DOMAIN="Azure"
          #EOF

          #
          # ===============================================================
          # 

       #   sed -i 's/^[ \t]*//g' ./.config
        #  make defconfig
      - name: 清理空间(Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
          tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true

      - name: 下载安装包
        run: |
          cd x-wrt 
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h
          #git reset --hard 639419e
          #git revert 1a9ee367343edce263f82cc91a49d796c9d45ea3
          #git revert 41e1e838fbbb0308ad7353a3714e04b8c4585e7e
      - name: SSH链接管理
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
         TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
         TELEGRAM_CHAT_ID: 1373335316         
           
      - name: 开始编译固件
        run: |
          #cp patches/110-mtd-limit-OTP-nvmem-to-non-nand-devices.patch x-wrt/target/linux/ipq40xx/patches-6.6/ 
          cd x-wrt
          #sed -i 's/CONFIG_PACKAGE_node=m/#CONFIG_PACKAGE_node=m/g' $GITHUB_WORKSPACE/myconfig/$CONFIG_FILENAME_FOR_2ND_COMPILE
          #sed -i 's/CONFIG_NODEJS_ICU_SMALL=y/#CONFIG_NODEJS_ICU_SMALL=y/g' $GITHUB_WORKSPACE/myconfig/$CONFIG_FILENAME_FOR_2ND_COMPILE
          #sed -i 's/CONFIG_PACKAGE_node-npm=m/#CONFIG_PACKAGE_node-npm=m/g' $GITHUB_WORKSPACE/myconfig/$CONFIG_FILENAME_FOR_2ND_COMPILE
          [ -d "build_dir" ] && sudo mv build_dir /mnt/ || ( mkdir build_dir;sudo mv build_dir /mnt/ )
          ln -s /mnt/build_dir .
          sudo mv dl /mnt/
          ln -s /mnt/dl .
          [ -d "bin" ] && sudo mv bin /mnt/ || ( mkdir bin;sudo mv bin /mnt/ )
          ln -s /mnt/bin .
          # rm dl/rrdtool*
          #wget https://oss.oetiker.ch/rrdtool/pub/archive/rrdtool-1.0.x/rrdtool-1.0.50.tar.gz
          #wget https://lftp.yar.ru/ftp/lftp-4.9.2.tar.xz
          #cd ../
          #echo cpu core=$(nproc)
          #make -j$(nproc) || make -j1 V=s
          #[ $? != 0 ] && make V=s || echo "build success"
          df -kh
          #rm `find $GITHUB_WORKSPACE/x-wrt/build_dir/ -name *.o`
          #du -a / | sort -n -r | head -n 20>/tmp/largefiles.txt
          #cat /tmp/largefiles.txt
          
          df -kh
          #make V=99 2>&1 |tee build.log
          #     echo "======================="
          #echo "Space usage:"
          #echo "======================="
          df -kh
          #echo "======================="
          #du -h ./ --max-depth=1
          #du -h ~/work/x-wrt --max-depth=1 || true
          #sudo find build_dir/ -name *.o -exec rm {} + 
      
      -  name: SSH connection for failure Debug
         if: ${{ failure() }}
           #uses: lhotari/action-upterm@v1
         uses: P3TERX/ssh2actions@main
         env:
          TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
          TELEGRAM_CHAT_ID: 1373335316
      - name: SSH connection for KERNEL MENU CONFIG
        if: env.KERNEL_MENUCONFIG == 'true'
          # uses: lhotari/action-upterm@v1
        uses: P3TERX/ssh2actions@main
        env:
         TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
         TELEGRAM_CHAT_ID: 1373335316
 
      - name: 再次编译固件 after updated kernel_menuconfig 
        if: env.BUILD_KERNEL_MODULES == 'true'
        run: |
         
           mkdir -p $DRIVERS_DIR

           #cp myconfig/$CONFIG_FILENAME_FOR_2ND_COMPILE x-wrt/.config
           cp myconfig/config.r619ac.3  x-wrt/.config     
           sed -i 's/# CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_SMP_CPU is not set/CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_SMP_CPU=y/g' x-wrt/.config
           sed -i 's/# CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_SMP_PROCESS is not set/CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_SMP_PROCESS=y/g' x-wrt/.config
           [ -e $KERNEL_CONFIG ] && cp -f $KERNEL_CONFIG $KERNEL_CONFIG_DIR/config-$KERNEL_VERSION
           cd x-wrt

           sudo rm -rf /usr/share/dotnet
           sudo rm -rf /opt/ghc
           sudo rm -rf "/usr/local/share/boost"
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
           #sudo rm -rf $GITHUB_WORKSPACE/lede
           echo cpu core=$(nproc)
           make -j$(nproc)
           cd ../
           cp -f x-wrt/build_dir/target-*/busybox-*/busybox-*/ipkg-install/bin/busybox $DRIVERS_DIR/busybox.$ROUTER_MODEL
           chmod 755 $DRIVERS_DIR/busybox.$ROUTER_MODEL
           copy_file.sh $DRIVERS_DIR/busybox.$ROUTER_MODEL

           sed -i 's/CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_SMP_CPU=y/# CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_SMP_CPU is not set/g' x-wrt/.config
           sed -i 's/CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_SMP_PROCESS=y/# CONFIG_BUSYBOX_CONFIG_FEATURE_TOP_SMP_PROCESS is not set/g' x-wrt/.config
           cp myconfig/config.r619ac.3  x-wrt/.config 
           cd x-wrt
           make -j$(nproc)
           df -kh
           [ $? != 0 ] && make V=s || echo "build success"
           cp -f bin/targets/ipq40xx/generic/openwrt-ipq40xx-generic-p2w_r619ac-128m-squashfs-sysupgrade.bin bin/targets/ipq40xx/drivers/  
           df -kh
      - name: SSH connection for failure Debug
        if: ${{ failure() }}
        #uses: lhotari/action-upterm@v1
        uses: P3TERX/ssh2actions@main
        env:
         TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
         TELEGRAM_CHAT_ID: 1373335316 
      - name: Prepare artifact
        run: |
          # mkdir -p ./artifact/firmware
          #mkdir -p ./artifact/package
          #mkdir -p ./artifact/buildinfo
          #mkdir -p $DRIVERS_DIR
          cp -rf `find x-wrt/build_dir/target*/linux*/linux-*/ -name *.ko|grep -v oot` $DRIVERS_DIR
          #cp -rf x-wrt/build_dir/target*/linux*/rtl8821cu*/rtl8821cu.ko $DRIVERS_DIR        
          #cp -f .config bin/
          #cp -f myconfig/config.$ROUTER_MODEL.? bin/
          #rm -rf $(find ./bin/targets/ -type d -name "packages")
          #cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          #cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          #cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
          cat `find x-wrt/bin/targets/ -name version.buildinfo`|head -1> BUILD_VERSION
          [ -s BUILD_VERSION ] && echo "BUILD_VERSION=_$(cat BUILD_VERSION)" >> $GITHUB_ENV 
          grep '^CONFIG_TARGET.*DEVICE.*=y' x-wrt/.config|head -1 | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          find x-wrt/bin/targets |grep kmod|tail -1|cut -d _ -f2|cut -d - -f1 > KERNEL_VER
          #strings $DRIVERS_DIR/ext4.ko |grep linux-|tail -1|tail -c15|cut -d - -f2 > KERNEL_VER
          #strings $DRIVERS_DIR/rtl8821cu.ko |grep linux-|tail -1|tail -c15|cut -d - -f2 > KERNEL_VER
          [ -s KERNEL_VER ] && echo "KERNEL_VER=_$(cat KERNEL_VER)" >> $GITHUB_ENV
          wget http://be6500.ddnsfree.com:8080/upload_firmware_config/${{ env.ROUTER_MODEL }}
          upload=`cat ${{ env.ROUTER_MODEL }}`
          echo "UPLOAD_ROUTER=$upload" >> $GITHUB_ENV
          echo "UPLOAD ROUTER=$upload" 
          #cd x-wrt
          #zip -r OpenWrt_${{env.bin}}_${{ env.DEVICE_NAME }}${{ env.BUILD_VERSION }}${{ env.FILE_DATE }}${{ env.KERNEL_VER}}.zip bin
      - name: zip bin directory
        run: |
          cd x-wrt
          zip -r OpenWrt_${{ env.bin }}_${{ env.DEVICE_NAME }}${{ env.BUILD_VERSION }}${{ env.FILE_DATE }}${{ env.KERNEL_VER}}.zip bin
      - name: 上传固件到Router
        id: trf_to_router
        if: env.UPLOAD_ROUTER== 'true' && !cancelled()
        run: | 
          cd x-wrt
          #zip -r OpenWrt_${{env.bin}}_${{ env.DEVICE_NAME }}${{ env.BUILD_VERSION }}${{ env.FILE_DATE }}${{ env.KERNEL_VER}}.zip bin
          copy_file.sh OpenWrt_${{ env.bin }}_${{ env.DEVICE_NAME }}${{ env.BUILD_VERSION }}${{ env.FILE_DATE }}${{ env.KERNEL_VER}}.zip     

      - name: 上传固件到github
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_${{env.bin}}${{ env.DEVICE_NAME }}${{ env.BUILD_VERSION }}${{ env.FILE_DATE }}${{ env.KERNEL_VER}}
           #OpenWrt_${{env.bin}}${{ env.ROUTER_MODEL }}
          path: x-wrt/bin
      - name: SSH connection for failure Debug
        if: ${{ failure() }}
        uses: P3TERX/ssh2actions@main
        env:
         TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
         TELEGRAM_CHAT_ID: 1373335316
        
      - name: Upload bin directory if failure
        uses: actions/upload-artifact@master
        if:  failure() 
        with:
          name: OpenWrt_${{env.bin}}_${{ env.DEVICE_NAME }}${{ env.BUILD_VERSION }}${{ env.FILE_DATE }}${{ env.KERNEL_VER}}
           #OpenWrt_${{env.bin}}${{ env.ROUTER_MODEL }}_failure
          path: x-wrt/bin


            #- name: Deliver buildinfo
            #uses: actions/upload-artifact@v2
            #with:
            #name: OpenWrt_buildinfo
            #path: ./artifact/buildinfo/

            
            #- name: Deliver package
            #uses: actions/upload-artifact@v2
            #with:
            #name: OpenWrt_package
            #path: ./artifact/package/

            #- name: Deliver firmware
            #uses: actions/upload-artifact@v2
        #with:
        #name: OpenWrt_firmware
        #path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true

